# Generated by Django 6.0.2 on 2026-02-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('program_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EVMSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('bcws_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bcwp_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acwp_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('eac_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cpi', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('spi', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('cv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sv', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='main_app.controlaccount')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='main_app.program')),
            ],
        ),
        migrations.CreateModel(
            name='CSVupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_file', models.CharField(max_length=255)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_upload', to='main_app.program')),
            ],
        ),
        migrations.AddField(
            model_name='controlaccount',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_accounts', to='main_app.program'),
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='main_app.controlaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EVMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(blank=True, max_length=200)),
                ('eoc', models.CharField(choices=[('Labor', 'Labor'), ('Material', 'Material'), ('ODC', 'ODC'), ('PCL', 'PCL')], max_length=50)),
                ('results', models.CharField(choices=[('Dollars', 'Dollars'), ('FTE', 'FTE'), ('Hours', 'Hours'), ('Direct', 'Direct')], max_length=50)),
                ('cam', models.IntegerField(max_length=50)),
                ('cobra_set', models.CharField(choices=[('EAC', 'EAC (Estimate at Completion)'), ('CEAC', 'CEAC (Cumulative EAC)'), ('BCWP', 'BCWP (Earned Value)'), ('BCWS', 'BCWS (Planned Value)'), ('ACWP', 'ACWP (Actual Cost)'), ('BAC', 'BAC (Budget at Completion)')], max_length=100)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('control_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evm_data', to='main_app.controlaccount')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evm_data', to='main_app.workpackage')),
            ],
        ),
    ]
