# Generated by Django 6.0.2 on 2026-02-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvupload',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='rows_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='rows_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvupload',
            name='rows_total',
            field=models.IntegerField(default=0),
        ),
    ]
