# Generated by Django 6.0.2 on 2026-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evmdata',
            name='cam',
            field=models.IntegerField(),
        ),
    ]
