# Generated by Django 6.0.2 on 2026-02-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_csvupload_errors_csvupload_rows_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlaccount',
            name='cam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='controlaccount',
            name='ipt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
