# Generated by Django 6.0.2 on 2026-02-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_controlaccount_cam_controlaccount_ipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='evmdata',
            name='csv_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.csvupload'),
        ),
    ]
