# Generated by Django 6.0.2 on 2026-02-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_evmdata_csv_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='evmdata',
            name='ipt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evmdata',
            name='cam',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
