# Generated by Django 6.0.2 on 2026-02-24 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_evmdata_ipt_alter_evmdata_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='evmdata',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evm_data', to='main_app.program'),
        ),
    ]
